version: '3'
services:
  botframework:
    image: "node:latest"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - .:/home/node/app
    ports:
      - "3000:3000"
      - "3978:3978"
    command: "npm start"
